config/routes.rb
Rails.application.routes.draw do
  root 'epicenter#feed'
  get 'show_user' => 'epicenter#show_user'
  get 'now_following' => 'epicenter#now_following'
  get 'unfollow' => 'epicenter#unfollowing'
  get 'tag_tweets' => 'epicenter#tag_tweets'

  resources :tweets
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tag.rb
class Tag < ApplicationRecord

has_many :tweet_tags
has_many :tweets, through: :tweet_tags

end

app/models/tweet.rb
class Tweet < ApplicationRecord
	belongs_to :user

	has_many :tweet_tags
	has_many :tags, through: :tweet_tags

	before_validation :link_check, on: :create
	validates :message, presence: true
	validates :message, length: {maximum: 250, too_long: "- if you need more than 250 characters, write a blog."}, on: :create
	after_validation :apply_link, on: :create

private
	def link_check
		if self.message.include? "https://"
			arr = self.message.split
			indx = arr.map { |x| x.include? "https://"}.index(true)
			self.link = arr[indx]

			if arr[indx].length > 23
				arr[indx] = "#{arr[indx][0..20]}..."
			end

			self.message = arr.join(" ")
		end	
	end
	def apply_link
		arr = self.message.split
		indx = arr.map { |x| x.include? "https://"}.index(true)
		if indx
		url = arr[indx]

		arr[indx] = "<a href='#{self.link}' target='_blank' >#{url} </a>"
		end
		self.message = arr.join(" ")
	end


end

app/models/tweet_tag.rb
class TweetTag < ApplicationRecord

	belongs_to :tweet
	belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         serialize :following, Array

         has_many :tweets

         mount_uploader :avatar, AvatarUploader

         validates :username, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :configure_permitted_parameters, if: :devise_controller?

	protected

	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :username, :bio, :location, :avatar, :following])
		
		devise_parameter_sanitizer.permit(:account_update, keys: [:name, :username, :bio, :location, :avatar, :following])
	end
end

app/controllers/epicenter_controller.rb
class EpicenterController < ApplicationController
  
  before_action :authenticate_user!
  
  def tag_tweets
    @tag = Tag.find(params[:id])
    
  end

  def feed
    @tweet = Tweet.new

  	@following_tweets = []

  	Tweet.all.each do |tweet|
  		if current_user.following.include?(tweet.user_id) || current_user.id == tweet.user_id
  		@following_tweets.push(tweet)
  	end
   end
  end

  def show_user
  	@user = User.find(params[:id])
  end

  def now_following
    current_user.following.push(params[:id].to_i)
    current_user.save

    redirect_to show_user_path(id: params[:id])
  end

  def unfollowing
    current_user.following.delete(params[:id].to_i)
    current_user.save

    redirect_to show_user_path(id: params[:id])
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_user!

  include TweetsHelper
  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.create(tweet_params)

    @tweet = get_tagged(@tweet)


    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:message, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/epicenter_helper.rb
module EpicenterHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
def get_tagged(tweet)
message_arr = @tweet.message.split

    message_arr.each_with_index do |word, index|
      if word[0] == "#"
        #create a new instance of Tag
        if Tag.pluck(:phrase).include?(word.downcase)
          #save that tag as a variable
          tag = Tag.find_by(phrase: word.downcase)
          else
            #create a new instance of Tag
          tag = Tag.create(phrase: word.downcase)
        end

        tweet_tag = TweetTag.create(tweet_id: @tweet.id, tag_id: tag.id)

        message_arr[index] = "<a href='/tag_tweets?id=#{tag.id}'>#{word}</a>"
      end
    end 

    @tweet.update(message: message_arr.join(" "))
    return tweet
end
end

app/views/epicenter/feed.html.erb
<div class= "container">
    <div class="row">
      <div class="col-md-3">
        <div class="panel panel-default">
         	<div style="background-color:#1DA1F2;" class="panel-heading">
            <h2 class="panel-title"></h2>
          	</div>
	          <div class="panel-body">
	              <% if current_user.avatar.blank? == false %>
	                  <%= image_tag current_user.avatar.url, size:25, class: "user-pic" %>
	            	<% end %>
	            	<ul style="list-style-type:none", class= "float">
			            <b><li><%= link_to current_user.name %>
			             </li></b> 
			            <li style="color:gray"> @<%= link_to current_user.username %>
			            </li>
		            </ul>
	           
		            <table>
	              <tr>
	                <th style="color:gray" id= "tbs"><%= link_to "Tweets" %></th> 
	                <th style="color:gray" id= "tab"><%= link_to "Following" %></th> 
	                <th style="color:gray"><%= link_to "Followers" %></th>
	              </tr> 
	              <tr>
	                <td class= "td" style="color:DodgerBlue;"><B>0</B></td> 
	                <td class= "td" style="color:DodgerBlue; width: 90px;"><b>22</b></td> 
	                <td class= "td" style="color:DodgerBlue;"><b>12</b></td>
	              </tr>
	            </table>
	        </div>
	          </div>
	         

         <div class="panel panel-default">
        <div class="panel-headingg">
          <h3 class="panel-title"><b>Trends For you</b> <a href="#">Change</a></h3>
        </div>
        <div class="panel-body">
          <a href="#"><b>@World cup final</b></a><br>
          <p>73.4k retweets</p>
          <a href="#"><b>@Trump</b></a><br>
          <p>100k retweets</p>
          <a href="#"><b>#NewMusicFriday</b></a><br><br>
          <a href="#"><b>@Codingnow</b></a><br>
          <p>35.2k retweets</p>
          <a href="#"><b>#Avlnews</b></a><br>
          
        </div>
  
      </div>

      </div>
  
		<div class= "col-md-6">

		<div class="panel panel-default" style= "height: 34px;">
	        <div class="panel-headin">

				<div><% if current_user.avatar.blank? %>
         			<%= image_tag "default.png" %>
	                  <% else %> 
	                  <%= image_tag current_user.avatar.url, size:25, class: "user" %>
	            	<% end %>

					<%= render 'tweets/form', tweet: @tweet %> </div>
			</div>
		</div>
		<div class="panel panel-default">
	        <div class="panel-body">

				<h1>@<%= current_user.username %>'s Twitter Feed</h1>

				<p>Here is what your friends are saying...</p>

				<% @following_tweets.each do |tweet| %>

					<p>@<%= link_to tweet.user.username, show_user_path(id: tweet.user.id) %></p>
					<p><%= tweet.message.html_safe %></p>

				<% end %>
			</div>
		</div>
	</div>
		<div class= "col-md-3">
			<div class="panel panel-default">
				<div class="panel-headingg">
	            <h2 class="panel-title"><b>Who to Follow</b> . <a href="#">View All</a> . <a href="#">Refresh</a> </h2>
	          	</div>
	          	<div class="panel-body">

	          	


	          		Eat grass, throw it back up bathe private parts with tongue then lick owner's face, or rub face on owner being gorgeous with belly side up.  Push your water glass on the floor drool lick the other cats but mesmerizing birds. Munch on tasty moths lick butt, yet sit on human they not getting up ever or spill litter box, scratch at owner, destroy all furniture, especially couch this human feeds me, i should be a god milk the cow dont wait for the storm to pass, dance in the rain. Catch mouse and gave it as a present refuse to leave cardboard box murf pratt ungow ungow, or cat not kitten around . 
	          	</div>
	          	<div class="panel-footer">
	          		<a href="#">Find people you know</a>
	          	</div>
			</div>

			<div class="panel panel-default">
				<div class="panel-body">
			      <ul style="list-style-type:none">
			        <li class="Footer-item ">© 2018 Twitter</li>
			        <li class="Footer-item"><a class="Footer-link" href="#">About</a> | <a class="Footer-link" href="#">Ads info</a> </li>
			        <li class="Footer-item"><a class="Footer-link" href="#">Help Center</a> | <a class="Footer-link" href="#">Jobs</a> </li>
			        <li class="Footer-item"><a class="Footer-link" href="/tos" rel="">Terms</a> | <a class="Footer-link" href="#">Marketing</a> </li>
			        <li class="Footer-item"><a class="Footer-link" href="#">Privacy policy</a> | <a class="Footer-link" href="#">Businesses</a> </li>
			        <li class="Footer-item"><a class="Footer-link" href="#">Cookies</a> | <a class="Footer-link" href="#">Developers</a> </li>
			      </ul>
			      
			    </div>
			 	<div class="panel-footer">
	          		<a href="#">Find people you know</a>
	          	</div>
		</div>
	</div>
</div>

app/views/epicenter/following.html.erb
<h1>Epicenter#following</h1>
<p>Find me in app/views/epicenter/following.html.erb</p>

app/views/epicenter/not_following.html.erb
<h1>Epicenter#not_following</h1>
<p>Find me in app/views/epicenter/not_following.html.erb</p>

app/views/epicenter/show_user.html.erb
<div class= "container">
    <div class="row">
      <div class="col-md-12">
        <div class="panel panel-default">
         	<div style="background-color:#1DA1F2; height: 171px;" class="panel-heading" id= "stretch">
         		
         		<% if current_user.avatar.blank? %>
         			<%= image_tag "default.png" %>
	                  <% else %> 
	                  <%= image_tag current_user.avatar.url, size:65, class: "user-pics" %>
	            	<% end %>
         		
            <h2 class="panel-title"></h2>
          	</div>

         
          	<div class="panel-heading" id= "stretchy">
          	
          		<table>
	              <tr>
	              	<th>  </th>
	                <th style="color:gray" id= "tbs"><%= link_to "Tweets" %></th> 
	                <th style="color:gray" class= "tab"><%= link_to "Following" %></th> 
	                <th style="color:gray" class= "tab"><%= link_to "Followers" %></th>
	                <th style="color:gray" id= "tabb"><%= link_to "Lists" %></th>
	                <th style="color:gray"><%= link_to "Moments" %></th>
	              
	              </tr> 
	              <tr>
	              	<td style= "width: 350px;">  </td>
	                <td class= "td" style="color:DodgerBlue;"><B>0</B></td> 
	                <td class= "td" style="color:DodgerBlue;"><b>22</b></td> 
	                <td class= "td" style="color:DodgerBlue;"><b>12</b></td>
	                <td class= "td" style="color:DodgerBlue;"><b>87</b></td>
	                <td class= "td" style="color:DodgerBlue; width: 510px;"><b>45</b></td>
	               
	              </tr>
	              <span id= "right">
	                	 <%= link_to '<button type="button" style="height: 36px;">Edit Profile</button>'.html_safe, edit_user_registration_path %>
	                </span>
	            </table>
					

          	</div>

          </div>
      </div>
  </div>
</div>


<div class= "container">
    <div class="row">
<div class="col-md-2">
        
<div>
<h3>@<%= @user.username %>'s Profile</h5>

<p>
	<%= @user.name %>
</p>

<p>
	<%= @user.location %>
</p>

<p>
	<%= @user.bio %>
</p>




</div>
</div>


	<div class="col-md-7">
		<div class="panel panel-default">
			<div class="panel-headingg">
				<h3>My Tweets</h3>
				<p>
	<% if current_user.following.include?(@user.id) %>
	<%= link_to "Unfollow", unfollow_path(id: @user.id), class: "bttn btn-default", id:"unfollow-btn" %>
		<% else %>
		<% if current_user.id != @user.id %>
		<%= link_to "Follow", now_following_path(id: @user.id), class: "btn btn-default" %>
		<% end %>
	<% end %>
</p>

<% @user.tweets.each do |tweet| %>
<p>@<%= link_to @user.username, show_user_path(id: tweet.user.id) %></p>
<p><%= tweet.message %></p>
<% end %>
			</div>
		</div>
	</div>


      <div class="col-md-3">
        <div class="panel panel-default">
        	<div class="panel-headingg">
          <h3 class="panel-title"><b>Trends For you</b> <a href="#">Change</a></h3>
        </div>
        <div class="panel-body">
          <a href="#"><b>@World cup final</b></a><br>
          <p>73.4k retweets</p>
          <a href="#"><b>@Trump</b></a><br>
          <p>100k retweets</p>
          <a href="#"><b>#NewMusicFriday</b></a><br><br>
          <a href="#"><b>@Codingnow</b></a><br>
          <p>35.2k retweets</p>
          <a href="#"><b>#Avlnews</b></a><br>
          
        </div>
        </div>
      </div>
    </div>
</div>

app/views/epicenter/tag_tweets.html.erb
<h1><%= @tag.phrase %></h1>

<% @tag.tweets.order(created_at: :desc).each do |tweet| %>
	<%= tweet.user.name %> <%= "@#{tweet.user.username}" %><br>
	&bull; <%= time_ago_in_words(tweet.created_at)%><br>

	<%= tweet.message.html_safe %><br>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheTwitter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body>
  <nav id = "nav" class="navbar navbar-default" >
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

          <%= link_to "Home", root_path, class: "navbar-brand" %>
        </div>
        <div class="float-right" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="/tweets"><span class="glyphicon glyphicon-flash"></span> Moments</a></li>
            <li><a href="#"><span class="glyphicon glyphicon-bell"></span> Notifications</a></li>
            <li><a href="#"><span class="glyphicon glyphicon-bell"></span> Messages</a></li>

          </ul>
          </div>

       <form class="navbar-form navbar-right">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Search">
              <button type="submit" class="btn btn-default">Submit</button>
            </div>
           

          </form>
          <ul class="nav navbar-nav navbar-right pull-right">
          <% if user_signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" style= "padding-bottom: 0px;">
                <% if current_user.avatar.blank? == false %>
                  <%= image_tag current_user.avatar.url, size:25, class: "user-pic-nav" %>
                <% end %> 


              <ul id = "text" class="dropdown-menu">
                <%= current_user.name %><br>
                @<%= current_user.username %> 
                <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>

            <li><%= link_to '<i class = "glyphicon glyphicon-comment"></i> Compose New Tweet'.html_safe, new_tweet_path %>
           </li>
        <% end %>
        </ul>
         </div>
       </div>
      </nav>
    <div class="container">

    <%= yield %>
    </div>


</body>
</html>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet, local: true) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="submit" style= "height: 55px;">
    <%= form.text_area :message, placeholder: "What's Happening?"%> 
    <span class="submit">
    <%= form.submit %></span>
  </div>

  <div class="field">
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tweets</h1>

<table>
  <thead>
    <tr>
      <th>Message</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= tweet.message.html_safe %></td>
        <td>
          <% unless tweet.user.avatar.url == nil %>
            <%= image_tag tweet.user.avatar.url, width: 50 %>
          <% end %>
          <%= link_to tweet.user.username, show_user_path(id: tweet.user.id) %></td>
        <td><%= link_to 'Show', tweet %></td>
        <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
        <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tweet', new_tweet_path %>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message:</strong>
  <%= @tweet.message.html_safe %>
</p>

<p>
  <strong>User:</strong>
  <%= link_to @tweet.user.username, show_user_path(id: @tweet.user.id) %>
</p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>